name: DentallApp.Backend

on: 
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev
env:
  DOTNET_VERSION: '8.x'

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Test
      run: |
       dotnet test ./tests/UnitTests/DentallApp.UnitTests.csproj -c Release

  chatbot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Test
      run: |
       dotnet test ./tests/ChatBot/Plugin.ChatBot.IntegrationTests.csproj -c Release

  database_testing:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.11.6
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: dentallapp_db_test
          MARIADB_ROOT_PASSWORD: 123456789
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Create .env files
        run: |
          cp ./tests/IntegrationTests/.env.test.example ./tests/IntegrationTests/.env.test
          cp ./.env.example ./.env
      - name: Test 
        run: |
          dotnet test ./tests/IntegrationTests/DentallApp.IntegrationTests.csproj -c Release